name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Hello word
      run: |
        echo " HEllo"

    - name: Run tests
      run: |
        python -m unittest discover
