name: Python CI

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create build directory and add files
      run: |
        mkdir -p build
        echo "Build output" > build/output.txt

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/*

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check if artifacts exist
      id: check-artifacts
      run: |
        if [ -d "build" ]; then
          echo "Artifacts found."
          echo "ARTIFACTS_EXIST=true" >> $GITHUB_ENV
        else
          echo "No artifacts found."
          echo "ARTIFACTS_EXIST=false" >> $GITHUB_ENV
        fi

    - name: Download build artifacts
      if: env.ARTIFACTS_EXIST == 'true'
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts

    - name: test
      run: make test